namespace Trash.Domain.Initializer
{
    using System.Collections.Generic;
    using Trash.Domain.Entities;

    public static partial class Initializer
    {
        static partial void InitializeParam(TrashContext ctx)
        {
            var transmissionTypes = new List<TransmissionType>
                                        {
                                            new TransmissionType { Title = "Механика"},
                                            new TransmissionType { Title = "Автомат"},
                                            new TransmissionType { Title = "Вариатор"},
                                            new TransmissionType { Title = "Робот"}
                                        };
            var driveTypes = new List<DriveType>
                                 {
                                     new DriveType { Title = "Передний"},
                                     new DriveType { Title = "Задний"},
                                     new DriveType { Title = "Полный"},
                                 };

            var detailTypes = new List<DetailType>()
                                  {
                                      new DetailType() { Title = "Дверь"},
                                      new DetailType() { Title = "Блок ДВС"},
                                      new DetailType() { Title = "МКПП"},
                                      new DetailType() { Title = "АКПП"},
                                      new DetailType() { Title = "ДВС"},
                                      new DetailType() { Title = "Капот"},
                                      new DetailType() { Title = "Дверь 5-я"},
                                      new DetailType() { Title = "Крышка багажника"},
                                      new DetailType() { Title = "Крыло"},
                                      new DetailType() { Title = "Поворотный кулак"},
                                      new DetailType() { Title = "Ступица"},
                                      new DetailType() { Title = "Раздатка"},
                                      new DetailType() { Title = "Бензобак"},
                                      new DetailType() { Title = "Бампер"},
                                      new DetailType() { Title = "Крыша"},
                                      new DetailType() { Title = "Порог"},
                                      new DetailType() { Title = "Генератор"},
                                      new DetailType() { Title = "ЭБУ ДВС"},
                                      new DetailType() { Title = "ЭБУ АКПП"},
                                      new DetailType() { Title = "Усилитель магнитолы"},
                                      new DetailType() { Title = "ЭБУ климатом"},
                                      new DetailType() { Title = "ЭБУ SRS"},
                                      new DetailType() { Title = "Электронный блок"},
                                      new DetailType() { Title = "ЭБУ ABS"},
                                      new DetailType() { Title = "ЭБУ ЭУР"},
                                      new DetailType() { Title = "Стойка"},
                                      new DetailType() { Title = "Амортизатор"},
                                      new DetailType() { Title = "Пружина"},
                                      new DetailType() { Title = "Амортизатор багажника"},
                                      new DetailType() { Title = "Рычаг"},
                                      new DetailType() { Title = "Тяга рулевая"},
                                      new DetailType() { Title = "Торсион"},
                                      new DetailType() { Title = "Болт"},
                                      new DetailType() { Title = "Стойка стабилизатора"},
                                      new DetailType() { Title = "Ремень ГРМ"},
                                      new DetailType() { Title = "Ролик натяжителя"},
                                      new DetailType() { Title = "Подшипник ступичный"},
                                      new DetailType() { Title = "Шаровая опора"},
                                      new DetailType() { Title = "Шланг тормозной"},
                                      new DetailType() { Title = "Втулка стабилизатора"},
                                      new DetailType() { Title = "Отопитель"},
                                      new DetailType() { Title = "Прокладка ДВС"},
                                      new DetailType() { Title = "Ремень"},
                                      new DetailType() { Title = "Фильтр воздушный"},
                                      new DetailType() { Title = "Прокладка"},
                                      new DetailType() { Title = "Подшипник выжимной"},
                                      new DetailType() { Title = "Кнопка ЭСП"},
                                      new DetailType() { Title = "Переключатель света фар"},
                                      new DetailType() { Title = "Реле"},
                                      new DetailType() { Title = "Брызговик"},
                                      new DetailType() { Title = "Подшипник подвесной"},
                                      new DetailType() { Title = "Наконечник рулевой"},
                                      new DetailType() { Title = "Сальник"},
                                      new DetailType() { Title = "Кольцо уплотнительное"},
                                      new DetailType() { Title = "Втулка стартера"},
                                      new DetailType() { Title = "Датчик"},
                                      new DetailType() { Title = "Втулка"},
                                      new DetailType() { Title = "Сайлентблок"},
                                      new DetailType() { Title = "Форсунка"},
                                      new DetailType() { Title = "Держатель глушителя"},
                                      new DetailType() { Title = "Диск сцепления"},
                                      new DetailType() { Title = "Распределитель зажигания"},
                                      new DetailType() { Title = "Стартер"},
                                      new DetailType() { Title = "Панель приборов"},
                                      new DetailType() { Title = "Приводной вал"},
                                      new DetailType() { Title = "Балка"},
                                      new DetailType() { Title = "Фара"},
                                      new DetailType() { Title = "Бачок омывателя"},
                                      new DetailType() { Title = "Бачок ГУР"},
                                      new DetailType() { Title = "Бачок расширительный"},
                                      new DetailType() { Title = "Бачок тормозной жидкости"},
                                      new DetailType() { Title = "Фонарь"},
                                      new DetailType() { Title = "Поворотник"},
                                      new DetailType() { Title = "Суппорт"},
                                      new DetailType() { Title = "Блок управления отопителя"},
                                      new DetailType() { Title = "Стекло"},
                                      new DetailType() { Title = "Стекло заднее"},
                                      new DetailType() { Title = "Глушитель"},
                                      new DetailType() { Title = "Стабилизатор"},
                                      new DetailType() { Title = "Тяга"},
                                      new DetailType() { Title = "Телевизор"},
                                      new DetailType() { Title = "Усилитель бампера"},
                                      new DetailType() { Title = "Кронштейн бампера"},
                                      new DetailType() { Title = "Шлейф руля"},
                                      new DetailType() { Title = "Коллектор выпускной"},
                                      new DetailType() { Title = "Турбина"},
                                      new DetailType() { Title = "Катализатор"},
                                      new DetailType() { Title = "Замок зажигания"},
                                      new DetailType() { Title = "Подрулевой переключатель"},
                                      new DetailType() { Title = "ГБЦ"},
                                      new DetailType() { Title = "Стекло люк"},
                                      new DetailType() { Title = "Зеркало"},
                                      new DetailType() { Title = "Вакуумный усилитель тормоза"},
                                      new DetailType() { Title = "Лонжерон"},
                                      new DetailType() { Title = "Передняя часть"},
                                      new DetailType() { Title = "Задняя часть"},
                                      new DetailType() { Title = "Насос ГУР"},
                                      new DetailType() { Title = "Гофра"},
                                      new DetailType() { Title = "Компрессор кондиционера"},
                                      new DetailType() { Title = "Корзина сцепления"},
                                      new DetailType() { Title = "Стеклоподъемник"},
                                      new DetailType() { Title = "Мотор фары"},
                                      new DetailType() { Title = "Подушка двигателя "},
                                      new DetailType() { Title = "Катушка зажигания"},
                                      new DetailType() { Title = "Подушка двигателя"},
                                      new DetailType() { Title = "Лючок бензобака"},
                                      new DetailType() { Title = "Ручка двери"},
                                      new DetailType() { Title = "Трубка кондиционера"},
                                      new DetailType() { Title = "Крышка двигателя"},
                                      new DetailType() { Title = "Радиатор"},
                                      new DetailType() { Title = "ГТЦ"},
                                      new DetailType() { Title = "Магнитола"},
                                      new DetailType() { Title = "Коллектор впускной"},
                                      new DetailType() { Title = "Накладка AIRBAG"},
                                      new DetailType() { Title = "Диск тормозной"},
                                      new DetailType() { Title = "Дроссельная заслонка"},
                                      new DetailType() { Title = "Кнопка регулировки зеркал"},
                                      new DetailType() { Title = "Блок предохранителей"},
                                      new DetailType() { Title = "Кнопка аварийки"},
                                      new DetailType() { Title = "Часы"},
                                      new DetailType() { Title = "Кнопка"},
                                      new DetailType() { Title = "Розетка 12V"},
                                      new DetailType() { Title = "Галогенка"},
                                      new DetailType() { Title = "Поводок дворника"},
                                      new DetailType() { Title = "Стекло лобовое"}
                                  };

            ctx.DriveTypes.AddRange(driveTypes);
            ctx.TransmissionTypes.AddRange(transmissionTypes);
        }
    }
}
